name: Publish

concurrency: all

on:
    push:
        tags: [ v* ]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-22.04

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: curl, intl, mbstring, openssl
                    coverage: none

            -   name: Cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

            -   name: Install dependencies
                run: composer install --no-interaction --no-ansi --quiet

            -   name: Coding Standards - PHP-CS-Fixer
                run: php vendor/bin/php-cs-fixer fix -v --dry-run --diff --config=.php-cs-fixer.dist.php

            -   name: Publish
                run: |
                    curl -X POST https://satis.wearedestination.com/api \
                        --fail-with-body \
                        --user ${{ secrets.SATIS_HTTP_AUTH }} \
                        --data '{"repository": "'"$GITHUB_REPOSITORY"'"}'
